### ISSUE TITLE
new line indentation after `&&` and `=` 

### ISSUE THREAD

**Issue by jney** [maxogden/standard-format#105]
i'm using last `standard-format` (1.6.6) and i've got the following input, that i expected not to be modified

``` javascript
var foo =
  'very long liiiiiiiiiiiiiiiiiiinnnnnnnnnnnnnnnnnnnnnnnnnneeeee'

var foo =
  Foo
  .bar
  .baz

foo &&
  bar
```

but it is indented like this : 

``` javascript
var foo =
'very long liiiiiiiiiiiiiiiiiiinnnnnnnnnnnnnnnnnnnnnnnnnneeeee'

var foo =
Foo
  .bar
  .baz

foo &&
bar
```

I'm not sure if it is the expected behaviour or a "bug"

**Comment by bcomnes** [comment]
We have some test cases for the indentation after a newline following the assignment operator (currently failing).  

We need to add one for `&&` I think, as well as track down the source of the issue.

**Comment by nrw** [comment]
i think this is related:

this input:
```js
var load = JSON.parse(value || JSON.stringify({
  playlists: true
}))
```
gets reformatted like this
```js
var load = JSON.parse(value || JSON.stringify({
    playlists: true
  }))
```

**Comment by feross** [comment]
You should use `standard --fix` instead of this package. `standard-format` isn't being actively maintained anymore.
