### ISSUE TITLE
ES5 Object Literal Getters and Setters

### ISSUE THREAD

**Issue by davidjamesstone** [maxogden/standard-format#108]
Consider

```
var obj = {
    get foo() {
        return Math.random();
    },
    set foo(value) {
        console.log('SET foo = '+value);
    },
};
```

Becomes

```
var obj = {
    get foo() {
        return Math.random();
    },
    set foo( value) {
        console.log('SET foo = '+value);
    },
};
```

Notice there's no space between 'foo' and the parens.
Also, an incorrect space is inserted before the 'value' argument of the setter.

If I insert a space between 'foo' and the parens, the formatter actually removes it.

I'm happy to try and work this out and submit a pull request - I just wanted to give you a heads up first.

Many thanks

**Comment by yoshuawuyts** [comment]
Confirmed, would be heaps nice if it was fixed ^__^.

**Comment by bcomnes** [comment]
Just ran standard-format against some ES6 today.  No bueno.  Any tests/poking around people are willing to do would be great.  I'll try to look at it soon but will be out of town for two weeks starting this weekend.

**Comment by feross** [comment]
You should use `standard --fix` instead of this package. `standard-format` isn't being actively maintained anymore.
