### ISSUE TITLE
does not support async functions

### ISSUE THREAD

**Issue by jonathanong** [maxogden/standard-format#109]
can't format my babel code because async functions are not supported :(

**Comment by feross** [comment]
ES6 support in esformatter is currently a bit lacking. As ES6 support improves in esformatter, standard-format will inherit those fixes.

**Comment by nickpoorman** [comment]
+1

**Comment by haywirez** [comment]
Any updates on this one?

**Comment by sheerun** [comment]
same

**Comment by sheerun** [comment]
Maybe you could switch to eslint for auto formatting?

**Comment by dotcypress** [comment]
Standart-format works fine with async functions now. 
But we have bug in dependency: https://github.com/millermedeiros/esformatter-semicolon-first/issues/3

For quick fix, just comment [this line](https://github.com/maxogden/standard-format/blob/master/rc/esformatter.json#L452)

**Comment by cyberwombat** [comment]
That dependency issue just got fixed btw. Current master now works.

**Comment by cyberwombat** [comment]
That dependency issue just got fixed btw. Current master now works for formatting. The linter however is still borked which prevents the formatter from working

**Comment by feross** [comment]
@cyberwombat How is the linter borked? You should be using `babel-eslint` with `standard` if you want ES6+ support. See http://standardjs.com/#can-i-use-a-custom-js-parser-for-bleeding-edge-es6-or-es7-support

**Comment by feross** [comment]
Also -- it may interest the folks who are following this issue to know that standard v8 is shipping with a new `--fix` option that is backed by eslint itself. So far in testing it works *MUCH* better than `standard-format` (which is backed by `esformatter`).

Give it a shot!

**Comment by cyberwombat** [comment]
@feross I mean the linter has not caught up. I am using sublimelinter-contrib-standard - I tried using another linter but the formatter and the other linters never seemed to agree on what is correct - . This linter does however it still marks async/await as invalid though the formatter has no issue with it anymore. Because the formatter fails on the async/await its a bit hard to lint and format. I will try your suggestions.

**Comment by feross** [comment]
You should use `standard --fix` instead of this package. `standard-format` isn't being actively maintained anymore.

**Comment by sheerun** [comment]
@feross Pro tip: remove issues section
