### ISSUE TITLE
Missing space before function parentheses after formatting code

### ISSUE THREAD

**Issue by feross** [maxogden/standard-format#116]
Moving from feross/standard. Original issue here: https://github.com/feross/standard/issues/264

With this code:

```js
var test = {
  hello() {}
}
test.hello()
```

Format code doesn't work:

![](https://cloud.githubusercontent.com/assets/1091472/9976421/12ddd0ce-5f16-11e5-8ca5-6b6465bec2d4.png)

**Comment by astanciu** [comment]
+1

**Comment by tusharmath** [comment]
+1

**Comment by tusharmath** [comment]
No Solution yet?

**Comment by jamesjoshuahill** [comment]
+1

**Comment by z0mt3c** [comment]
+1

**Comment by sorahn** [comment]
This breaks basically every single component file in a ES6 react project now. :(

```javascript
class Foo extends React.Component {
  componentWillMount () {}
  componentDidMount () {}
  componentWillReceiveProps () {}
  shouldComponentUpdate () {}
  componentWillUpdate () {}
  componentDidUpdate () {}
  componentWillUnmount () {}
  render () {}
}
```

**Comment by janecakemaster** [comment]
any word on when this will be fixed yet?

**Comment by feross** [comment]
@janecakemaster Hi! This package needs some love :) All the maintainers would love to fix it, but we're really busy! A pull request would be lovely!

**Comment by janecakemaster** [comment]
@feross i'd love to help, is there anything i can read up on to get started? never worked on a package like this before

**Comment by chenxsan** [comment]
Thought this issue is related to https://github.com/millermedeiros/esformatter/issues/368.

**Comment by feross** [comment]
@janecakemaster Yeah! The package uses `esformatter` to actually format the code. You can read about it here: https://www.npmjs.com/package/esformatter

Essentially, we pass it a configuration specifying how we want the code to be formatted and it does it for us. There's been lots of progress on `esformatter` since we created `standard-format` so there are probably lots of new "rules" we can add to the configuration file to do a better job with formatting.

Happy to add you (or anyone else who is reading this) as a maintainer after one or two good PRs. :smile:

**Comment by janecakemaster** [comment]
damn that's a lot of configs to go through. i'll take a look in the next week or so when i've got spare time

**Comment by feross** [comment]
@janecakemaster Sounds good.

**Comment by MatthewOverall** [comment]
any further updates on this issue?

**Comment by hxshandle** [comment]
any updates? I met the same problem.

**Comment by bcomnes** [comment]
@hxshandle we are moving towards using the --fix flag provided by eslint directly so we don't have to maintain two rulesets.  I believe the latest standard has this already.

**Comment by feross** [comment]
This issue is fixed if you use the new formatter: `standard --fix`.

Ensure you're using the latest `standard`, version 8.0.0. You can check with `standard --version`.
