### ISSUE TITLE
arrow function padding

### ISSUE THREAD

**Issue by Janpot** [maxogden/standard-format#121]
standard-format doesn't remove padding on arrow functions.

example:

``` js
var x = () => {

  console.log('hello world')

}
```

**Comment by feross** [comment]
PR welcome! The issue might be as simple as updating the version of esformatter used to improve ES6 support. Or, perhaps changing one of the rules in the esformatter config file.

**Comment by feross** [comment]
You should use `standard --fix` instead of this package. `standard-format` isn't being actively maintained anymore.
