### ISSUE TITLE
ES6 object literal shorthand formatted badly

### ISSUE THREAD

**Issue by Janpot** [maxogden/standard-format#122]
Objects defined as follows:

```js
var x = {
  y,
  z
}
```

get formatted like:

```js
var x = {
  y,
z}
```

**Comment by feross** [comment]
PR welcome! The issue might be as simple as updating the version of esformatter used to improve ES6 support. Or, perhaps changing one of the rules in the esformatter config file.

**Comment by Flet** [comment]
This looks to be a duplicate of https://github.com/maxogden/standard-format/issues/88
