### ISSUE TITLE
Bump esformatter-jsx dependency

### ISSUE THREAD

**Issue by LinusU** [maxogden/standard-format#128]
`esformatter-jsx` was just upgraded to stop using the deprecated Babel 5.x. This is good since it doesn't output the deprecation warning when installing standard. Can we bump the dependency here?

See royriojas/esformatter-jsx#38

**Comment by feross** [comment]
Sure thing. Published as 2.1.0.

**Comment by bcomnes** [comment]
Thanks!  Saw a note about babel last night but didn't get a chance to fix it.

**Comment by LinusU** [comment]
Thanks :+1:
