### ISSUE TITLE
ES6 Object Literals Not Formatting Correctly.

### ISSUE THREAD

**Issue by bcomnes** [maxogden/standard-format#129]
Formats enhanced ES6 object literals to:

```
  fubar ({a, b}) {
    baz('test', {
      a,
    b})
  }
```

cc @mblakele from https://github.com/feross/standard/issues/339

**Comment by fritx** [comment]
+1

**Comment by joseluisq** [comment]
Also, a related issue from https://github.com/stephenkubovic/atom-standard-formatter/issues/32

**Comment by joseluisq** [comment]
:+1:

**Comment by feross** [comment]
You should use `standard --fix` instead of this package. `standard-format` isn't being actively maintained anymore.
