### ISSUE TITLE
Not supporting the ES6 Class methods

### ISSUE THREAD

**Issue by davesnx** [maxogden/standard-format#134]
Hello,

I'm using standard for almost every project that I'm working on, as a linter on build/pr-check and also in the IDE. 

I have the issue of standard-format when you are working on ES6 with Classes with the space after the method definition, is reformating the code 

``` es6
class ClassName {
  constructor () {

  }
}
```

**into**

``` es6
class ClassName {
  constructor() {

  }
}
```

I check it with the CLI command, Sublime and Atom plugin, I didn't know If someone is watching this issue, but on the standard linter is giving me the error on the reformated code, and also, the space after the definition on the function is on the standard basics.

Thanks for create the repo, apart of that, it's pretty nice.

**Comment by zeke** [comment]
See also #75 and #111

**Comment by bcomnes** [comment]
Standard-format is in need of some code sprints to bring in ES6 support.  Thank you for the report!

**Comment by davesnx** [comment]
So sorry @zeke, for report more than twice the same issue :disappointed:

**Comment by tomkur** [comment]
:+1:

**Comment by feross** [comment]
You should use `standard --fix` instead of this package. `standard-format` isn't being actively maintained anymore.
