### ISSUE TITLE
confused with es6 getter/setter

### ISSUE THREAD

**Issue by feross** [maxogden/standard-format#138]
_Moved from @diasdavid's issue https://github.com/feross/standard/issues/316:_

It seems that when `standard --format`catches a es6 getter/setter, it changes its format and than reports a codestyle error, see example below

``` JavaScript
var log = ['test']
var obj = {
  get latest () {
    if (log.length === 0) return undefined
    return log[log.length - 1]
  }
}
console.log(obj.latest)
```

The right space was there, but then

``` bash
» standard --format troll.js
standard: Use JavaScript Standard Style (https://github.com/feross/standard)
  /Users/david/Documents/code/standard-troll/troll.js:3:13: Missing space before function parentheses.
```

Fixing the problem and running `standard` returns no errors, but then if `standard --format`is executed, it will remove the space again and report an error

**Comment by la-yumba** [comment]
I still see this problem, why has it been closed?

**Comment by feross** [comment]
@la-yumba The issue is not closed. It was moved from the `standard` repo to this repo, which is `standard-format`.

**Comment by feross** [comment]
You should use `standard --fix` instead of this package. `standard-format` isn't being actively maintained anymore.
