### ISSUE TITLE
Formatting of arrow-function inconsistent with StandardJS 

### ISSUE THREAD

**Issue by nknapp** [maxogden/standard-format#139]
The following snippet is an example that is correctly formatted (according to `standard`):

``` js
window.abc = (param) => JSON.stringify({
  param: param
})
```

`standard --format` changes the indentation of the last two lines and `standard` returns an error for the result:

``` js
window.abc = (param) => JSON.stringify({
    param: param
  })
```

Errors:

```
standard: Use JavaScript Standard Style (https://github.com/feross/standard) 
 .../test.js:2:5: Expected indentation of 2 space characters but found 4.
 .../test.js:3:3: Expected indentation of 0 space characters but found 2.
```

**Comment by feross** [comment]
You should use `standard --fix` instead of this package. `standard-format` isn't being actively maintained anymore.
