### ISSUE TITLE
Space being added after defaulted function parameters.

### ISSUE THREAD

**Issue by 5310** [maxogden/standard-format#140]
Coming from the Atom Standard Formatter package (which itself is v1.2.1), which uses `standard-format` v1.6.10 

I notice that space is being added after function parameters with defaults before a comma, like after `x = 0`:

```
let f = (x = 0 , a = 1) => x === 0 ? a : f(x - 1, a * x)
```

No space is added after the undefaulted first `x` in the following example, or after either example's `a = 0` parameter:

```
let f = (x, a = 1) => x === 0 ? a : f(x - 1, a * x)
```

**Comment by lygstate** [comment]
Ping for this.

**Comment by joseluisq** [comment]
Also, a related issue from https://github.com/stephenkubovic/atom-standard-formatter/issues/32

**Comment by joseluisq** [comment]
:+1:

**Comment by samuelmasuy** [comment]
Has it been resolved?

**Comment by feross** [comment]
You should use `standard --fix` instead of this package. `standard-format` isn't being actively maintained anymore.

**Comment by joseluisq** [comment]
@feross 👍
