### ISSUE TITLE
Custom Parser Option?

### ISSUE THREAD

**Issue by jescalan** [maxogden/standard-format#144]
I see a lot of issues about ES6 here, and it seems like it's not a simple task to add support for this. Standard itself passes the issue off to others by simply [accepting custom parsers](https://github.com/feross/standard#can-i-use-a-custom-js-parser-for-bleeding-edge-es6-or-es7-support), which actually works quite well in my experience. Using the babel-eslint parser shown in the example linked, there's pretty good support all the way through es7.

It's possible that I entirely do not understand how this project works and this would not be possible, but I'm curious whether it would be possible to just add support for accepting a custom parser like standard itself does. If so and I'm given a push in the right direction, I'd be happy to help!

**Comment by Flet** [comment]
This project is really just  an [esformatte](https://github.com/millermedeiros/esformatter) configuration. Currently, esformatter will *parse* ES6, but not all the hooks have been created to format it to the level folks require. 

Supporting different parses would be a feature of esformatter itself that would need to be created. Unfortunately just about all the parsers are built to completely ignore whitespace and formatting as they are not important to to the interpretation of lines of code.

Any improvements that can be made to esformatter itself to add hooks to new ES6 things would benefit this project.

**Comment by millermedeiros** [comment]
FYI, I have a working branch using babylon (babel-parser). Will probably start using it in the future. That will allow us to introduce support for experimental features and probably remove the need of a custom parser for most of the cases.

**Comment by bcomnes** [comment]
Thank you for the update and great work @millermedeiros !

**Comment by zeke** [comment]
Thanks for starting this thread, @jenius!

@millermedeiros is your branch public?

**Comment by zeke** [comment]
Ahh I see https://github.com/millermedeiros/esformatter/issues/398

**Comment by jenius** [comment]
Looks like the branch has been merged now, whoo! Maybe we can make this happen?

**Comment by mmazzarolo** [comment]
Hi!
Any news? Is it possible to use a custom parser now?

**Comment by bcomnes** [comment]
Apologies, I've not had any time to work on this.  If anyone is interested and has time, getting this in would probably be a major step forward for the formatter.  

I don't have much time for this in the foreseeable future, and will reach out to other standard contributors to help get more help on board, but someone stepping up would probably make it happen the fastest.

**Comment by krokofant** [comment]
This issue prevents me from finding any use of standard-format, sadly. I heavily use *class properties*.

**Comment by feross** [comment]
@krokofant You might want to install the latest beta of `standard` which exposes ESLint's built-in formatter. It's not perfect but it might help you out.

```
npm install -g standard@beta
```

Then run:

```
standard --fix
```

**Comment by feross** [comment]
You should use `standard --fix` instead of this package. `standard-format` isn't being actively maintained anymore.
