### ISSUE TITLE
Removing too many semicolons in empty while

### ISSUE THREAD

**Issue by diesire** [maxogden/standard-format#149]
`standard-format v2.1.1`

Expected

``` js
function Camera () {}

Camera.prototype.drawColumn = function (column, ray, angle, map) {
  var hit = -1
  while (++hit < ray.length && ray[hit].height <= 0);

  for (var s = ray.length - 1; s >= 0; s--) {
    // ...
  }
}
```

Result

``` js
function Camera () {}

Camera.prototype.drawColumn = function (column, ray, angle, map) {
  var hit = -1
  while (++hit < ray.length && ray[hit].height <= 0)

  for (var s = ray.length - 1; s >= 0; s--) {
    // ...
  }
}
```

The semicolon after the while is deleted, changing function result and generating two new warnings

![image](https://cloud.githubusercontent.com/assets/1185591/13323128/4b11ca4c-dbd8-11e5-97d2-047fdd91d001.png)

**Comment by feross** [comment]
You should use `standard --fix` instead of this package. `standard-format` isn't being actively maintained anymore.
