### ISSUE TITLE
History of this module

### ISSUE THREAD

**Issue by cdaringe** [maxogden/standard-format#154]
hi all!

im curious why this module uses esformatter vs eslint if standard uses eslint under the hood.  i have had issues with `eslint --fix`, and was surprised when `standard-format -F` worked when eslint --fix did not.

was `esformatter` chosen because `--fix` was not previously available, or because `--fix` has not met expectations?

just curious!

thanks!

**Comment by feross** [comment]
This package was written before `--fix` was available.
