### ISSUE TITLE
Don't format multi-slash line comments

### ISSUE THREAD

**Issue by pluma** [maxogden/standard-format#155]
As a rule: a line comment should be left alone if the first character in the comment (i.e. following the two leading slashes) is another slash.

Currently this:

```js
////////////////////////
/// hello            ///
////////////////////////
```

gets formatted to this:

```js
// //////////////////////
// / hello            ///
// //////////////////////
```

I'm not sure whether this is a valid concern but these comments may have special semantics for post-processors (similar to jsdoc/javadoc style comments).

**Comment by feross** [comment]
`standard` currently requires all inline comments (`//`) to be followed by a space character, so this is working as intended.

**Comment by pluma** [comment]
Fair enough. FYI: we'll probably be able to work around this issue as most of the post-processors have been removed.
