### ISSUE TITLE
new statements with linebreaks and comments break

### ISSUE THREAD

**Issue by tmcw** [maxogden/standard-format#156]
Hi there Max!

This is one of those 1% of suspected compiler bugs that end up being compiler bugs :)

This input:

```js
var foo = new // ARRAY_COPY(
  Date();

console.log(foo);
```

Runs correctly with node:

```
~/src/decode-webp〉node formatter-bug.js
Thu Mar 31 2016 18:33:54 GMT-0400 (EDT)
```

After `standard-format`:

```js
~/src/decode-webp〉standard-format formatter-bug.js
var foo = new // ARRAY_COPY(Date()

console.log(foo)
```

Which is invalid, and crashes node.

**Comment by tmcw** [comment]
Bug is upstream in esformatter: https://github.com/millermedeiros/esformatter/pull/439

**Comment by tmcw** [comment]
semver will magically upgrade to 0.9.4 of esformatter, and the fix is in there https://github.com/millermedeiros/esformatter/blob/master/CHANGELOG.md#v094-2016-05-25

**Comment by yoshuawuyts** [comment]
hah, that's a cute lil bug :sparkles:
