### ISSUE TITLE
stream format one file only

### ISSUE THREAD

**Issue by gautaz** [maxogden/standard-format#157]
Hello,

I probably missed something but I have tried different command line options of *standard-format* in order to comply with this [vim-autoformat](https://github.com/Chiel92/vim-autoformat) prerequisite:

>The formatprogram must read the unformatted code from the standard input, and write the formatted code to the standard output.

This is detailed [here](https://github.com/Chiel92/vim-autoformat#how-can-i-change-the-behaviour-of-formatters-or-add-one-myself).

Even when using the following syntax:

```bash
standard-format < /some/path/file.js
```

*standard-format* is still concatenating all the javascript files present in the current directory additionally with `/some/path/file.js`. So for now I did not find the right way to integrate *standard-format* with *vim-autoformat*.

Does someone have any suggestion on this particular subject ?

**Comment by feross** [comment]
You need to pass the argument `-` in order to signal stdin.

`standard-format -`

**Comment by gautaz** [comment]
@feross Thank you for the hint !

Perhaps it would be interesting to include this in the `readme.md` along with the other options?
