### ISSUE TITLE
Native thread-sleep not available

### ISSUE THREAD

**Issue by itlodge** [maxogden/standard-format#159]
Hi, 
     Every time I run 'standard-format', there is a warning. Can you solve it? 
```javascript
Native thread-sleep not available.
This will result in much slower performance, but it will still work.
You should re-install spawn-sync or upgrade to the lastest version of node if possible.
Check /usr/lib/node_modules/standard-format/node_modules/esformatter/node_modules/npm-run/node_modules/spawn-sync/error.log for more details
```

**Comment by chenxsan** [comment]
What is the output of `node -v` on your system?

You might need upgrade you nodejs.

**Comment by bcomnes** [comment]
One of the deps is using spawn-sync, which started doing some really not cool stuff with native dependencies underneath us.  

We need to remove whatever is using it, either by updating our deps to see if that fixes it, or by finding an alternative library for whatever is using it. 

PRs definately welcome on this one.

**Comment by feross** [comment]
This looks like an issue with esformatter. @itlodge Can you open an issue on their repo? https://github.com/millermedeiros/esformatter

**Comment by itlodge** [comment]
@chenxsan , thanks for your advice. Node 0.10.35 will cause this problem and Node 4.3.1 won't.
