### ISSUE TITLE
semicolon at end of string literal incorrectly removed

### ISSUE THREAD

**Issue by mvilrokx** [maxogden/standard-format#162]
I have a ES6 Template Literal that ends with a semicolon (;) and a carriage return:

```
    overrides = `${overrides}  ${override}: ${cssProperties[override]};
`
```

When running standard-format it incorrectly removes the ; from the Template Literal.

**Comment by feross** [comment]
You should use `standard --fix` instead of this package. `standard-format` isn't being actively maintained anymore.
