### ISSUE TITLE
Deleting newline character from backticked string

### ISSUE THREAD

**Issue by Xavdidtheshadow** [maxogden/standard-format#163]
Bear with me- I'm new to standard. I'm using `standard-format` in conjunction with the sublime extension to run it on save. 

My file is something like this:

```javascript
let line = `This should include a break\n`
```

which gets formatted as 

```javascript
let line = `This should include a break
`
```

which removed the explicit newline character. While it still works it's a lot less clear. Is this intended behavior or is there a way around this besides 
```javascript
let line = `This should include a break` + "\n"`
```

which sort of defeats the point. Thanks!

**Comment by feross** [comment]
This should not happen. PR welcome to fix it!

**Comment by Xavdidtheshadow** [comment]
After much digging, it turns out it's an open bug with babel (and by extension esformatter). The fix will trickle down to y'all once versions have been updated. 

See https://github.com/millermedeiros/esformatter/issues/414 and https://phabricator.babeljs.io/T6833

**Comment by feross** [comment]
Cool, will close this then.
