### ISSUE TITLE
Made gulp plugin...feedback?

### ISSUE THREAD

**Issue by Andruj** [maxogden/standard-format#164]
I use this a lot in my code, but I have always wanted a version that was not editor dependent (like the atom-standard-formatter). I use gulp a lot, and thought I would post this here in case anyone else wants it. Any feedback is welcome! 

http://github.com/andruj/gulp-standard-format

**Comment by feross** [comment]
You should use `standard --fix` instead of this package. `standard-format` isn't being actively maintained anymore.
