### ISSUE TITLE
feature request: unify standard and standard-format file inputs

### ISSUE THREAD

**Issue by cdaringe** [maxogden/standard-format#166]
standard: `standard "src/**/*.js" "test/**/*.js"`
standard-format: `standard-format -w "src/**/*.js" "test/**/*.js" # <== no worky, but would be great to "worky"`

let me know if you think that's a reasonable request!  obviously not high priority :)

**Comment by Flet** [comment]
Huh, this seems reasonable to me!

**Comment by feross** [comment]
You should use `standard --fix` instead of this package. `standard-format` isn't being actively maintained anymore.
