### ISSUE TITLE
Not adding a space where required

### ISSUE THREAD

**Issue by matthewadams** [maxogden/standard-format#167]
Steps to repro:

```
$ echo "var x = {a:1,b:2}" > x.js
$ standard-format x.js
var x = {a: 1,b: 2}
```

The output should be `var x = {a: 1, b: 2}`, where there's a space between the `,` & `b`.

**Comment by feross** [comment]
You should use `standard --fix` instead of this package. `standard-format` isn't being actively maintained anymore.
