### ISSUE TITLE
Incorrect indentation on promise then/catch

### ISSUE THREAD

**Issue by McOmghall** [maxogden/standard-format#170]
Creating an angular style promise like this

```
service.then(function success (result) {
  a()
}).catch(function error (result) {
  b()
})
```

Results in the final `.catch` callback lacking 2 spaces of indentation and failing linting, might be because `catch` is interpreted like the js reserved word?

**Comment by feross** [comment]
You should use `standard --fix` instead of this package. `standard-format` isn't being actively maintained anymore.
