### ISSUE TITLE
report error for valid if statement

### ISSUE THREAD

**Issue by futurist** [maxogden/standard-format#171]
below code is valid if statement, but cannot be formatted:

``` js
      if(!data) getData(url)
      else{
        play()
      }
```

But cannot be formatted, due to parse error

when changed as below:

``` js
      if(!data) { getData(url) }
      else{
        play()
      }
```

It's ok to be formatted.

**Comment by feross** [comment]
You should use `standard --fix` instead of this package. `standard-format` isn't being actively maintained anymore.
