### ISSUE TITLE
server side js binary cannot be formated

### ISSUE THREAD

**Issue by futurist** [maxogden/standard-format#172]
server side js file as executable binary which has `chmod +x` for attribute, as below:

```js
#!/usr/bin/env node

var http = require('http')
...
```

cannot be formatted, report error. should it be a issue?
Hope for `standard` format the node server module also

**Comment by chenxsan** [comment]
I don't think it has something to do with the `server side binary`. Maybe you had some new syntax in ES2005/ES2006 which are not supported by `standard-format` now.

**Comment by feross** [comment]
Yeah, this is most likely due to `standard-format` not supporting some fancy ES6 you're using. This is a known issue with the formatter.
