### ISSUE TITLE
Enabling standardFormat.formatOnSave keep on showing file as unsaved.

### ISSUE THREAD

**Issue by Ankitdave87** [maxogden/standard-format#176]
After enabling standardFormat.formatOnSave file always stays unsaved. It format code correctly but after that it starts showing file as not saved and for saving file must be closed once.

**Comment by chenxsan** [comment]
@Ankitdave87 this is actually a vscode-standard-format bug.

**Comment by feross** [comment]
@chenxsan thanks, closing. please share a link if you have one.
