### ISSUE TITLE
Depreciate this module and use standard --fix instead

### ISSUE THREAD

**Issue by bcomnes** [maxogden/standard-format#179]
I think we should depreciate this module, and use the --fix flag instead.

Things that need to happen: 

- [ ] Create some kind of stdin/stdout interface for the --fix rules in standard.
- [ ] Update all the editor plugins to default to using `standard --fix` rules instead of this module.

I've been meaning to get around to doing some of this work for a while, but I just haven't brought myself to do it.  Any takers?  Anyone want to pitch in?

**Comment by chenxsan** [comment]
[vscode standard-format](https://github.com/chenxsan/vscode-standard-format) was already deprecated. And we moved to [vscode standardjs](https://github.com/chenxsan/vscode-standardjs) using `standard --fix`.

**Comment by feross** [comment]
@bcomnes +1 Let's do this. One less thing to maintain! 😌 

I think the first item in the list is already done. You can use `standard --fix --stdin`, as I think you probably discovered while updating the sublime formatter plugin ;)

For the second point, do you know which editor plugins need to be updated?

**Comment by feross** [comment]
I just deprecated `standard-format` on npm.

```
npm WARN deprecated standard-format@2.2.3: standard-format is deprecated in favor of a built-in autofixer in 'standard'. Usage: standard --fix
```

I'm going to update the readme on this repo and close all the issues now.

**Comment by feross** [comment]
Apologies for the one-time notification spam!

- All issues are now closed, with a comment telling people to use `standard --fix`
- Package is deprecated on npm.
- Updated readme to make it clear that this is deprecated.
- Published updated readme to npm, so it shows up on their site.

And, now, I'll close this issue.

`standard-format` was a great project! It was crucial in getting people to use `standard` in the early days! I just want to thank everyone who sent in a PR, or opened an issue, or helped people in issue comments. 🎉 🎉 

Huge thanks to @jb55, @bcomnes, and @Flet for doing the bulk of the maintenance and hard work to make `standard-format` work. Also, shoutout to @maxogden for seeing the need for a formatter and creating the initial version. You all are heroes! 🍻

**Comment by Flet** [comment]
Thanks for doing this!
