### ISSUE TITLE
standard-format codebase should be treated with standard format

### ISSUE THREAD

**Issue by bcomnes** [maxogden/standard-format#18]
I'm in the 'run the correct auto-formatter on every save' camp, and i've been noticing that a lot of the code in this repo is getting transformed by standard-format in ways that go beyond what I think it should.

Take for example in `test/multiline.js`
```js
var program =
    'var x = 1\n' +
    '\n'
```
gets transformed to:
```js
var program = 'var x = 1\n' +
'\n'
```
This seems a bit too aggressive (trying to fix in https://github.com/bcomnes/standard-format/tree/assignment but totally stuck... help appreciated).

Thoughts?

**Comment by jb55** [comment]
We just switched to esformatter and the default settings we are using are a bit aggressive. I noticed a lot of `">=1"` settings when most of these should be set to -1 (no touchy)

**Comment by feross** [comment]
Yep, these all started out aggressive but I support relaxing them so they
don't touch things that aren't considered errors

**Comment by bcomnes** [comment]
Any ideas on the above example?  I can't seem to find a way to kill that behavior.

**Comment by jb55** [comment]
This should be fixed now, let me know.

**Comment by bcomnes** [comment]
Sweet!  I'll test it out.

**Comment by bcomnes** [comment]
@jb55 Looking good!  I'll reopen specific issues I run into from here.
