### ISSUE TITLE
Code is being changed by the standard-format

### ISSUE THREAD

**Issue by alexsorokoletov** [maxogden/standard-format#182]
Hi!
I initially found it as a problem with vscode-standard-format but then decided to check the `standard-format` and `standard` tools as well.
We have code
```
function NodeListToArray(nl) {
    for(var a=[], l=nl.length; l--; a[l]=nl[l]);
    return a;
}

```

Running standard-format over it produces incorrect code:
```
$ standard-format 1.js         
function NodeListToArray (nl) {
  for (var a = [], l = nl.length; l--; a[l] = nl[l])
    return a
}

```

Tried same code with `standard 1.js --fix`, produces just formatted code (no semantic change).

Please advise.

**Comment by feross** [comment]
`standard-format` is deprecated, so you should use `standard --fix` instead. This command fixes a lot, but not all errors. Fortunately, more errors become fixable with each release.

**Comment by Flet** [comment]
@alexsorokoletov:
Sam Chen's [vscode-standardjs](https://marketplace.visualstudio.com/items?itemName=chenxsan.vscode-standardjs) plugin includes a command to fix errors using `--fix`:
<img width="475" alt="screen shot 2016-12-04 at 10 35 33 pm" src="https://cloud.githubusercontent.com/assets/360233/20873892/0bbac0f0-ba72-11e6-9c8c-49a605aa07da.png">

**Comment by alexsorokoletov** [comment]
Thank you, guys.
