### ISSUE TITLE
Formatter kills empty lines

### ISSUE THREAD

**Issue by jb55** [maxogden/standard-format#2]
example:

before:
```js
function a() {
}

function b() {
}
```

after:
```js
function a() {
}
function b() {
}
```

don't think this is correct

**Comment by maxogden** [comment]
agreed, it should only convert 3+ newlines into 2, not 2 into 1

**Comment by jb55** [comment]
> agreed, it should only convert 3+ newlines into 2, not 2 into 1

does `standard` have an opinion about this? The rules don't mention it. I know some people like extra whitespace between functions for readability.

**Comment by jb55** [comment]
nm, it looks likes standard does report multiple lines as errors
