### ISSUE TITLE
Separate multiple var declaration

### ISSUE THREAD

**Issue by mightyiam** [maxogden/standard-format#22]
Turn

``` js
var foo,
  bar
```

Into

``` js
var foo
var bar
```

**Comment by jb55** [comment]
Looks like we'll need to write up an esformatter plugin for this one

**Comment by mightyiam** [comment]
Thanks and good luck.

**Comment by jb55** [comment]
Looks like this plugin does this! https://github.com/twolfson/esformatter-var-each

**Comment by jb55** [comment]
Fixed in a65c2d1

**Comment by jb55** [comment]
This break some tests actually, reopening for now until I can figure out what's going on

**Comment by devonbl** [comment]
is there any movement on this?

**Comment by feross** [comment]
You should use `standard --fix` instead of this package. `standard-format` isn't being actively maintained anymore.
