### ISSUE TITLE
Remove padding newlines after curly braces

### ISSUE THREAD

**Issue by mightyiam** [maxogden/standard-format#23]
Turn
```js
var foo = function () {

  bar()
}
```
Into
```js
var foo = function () {
  bar()
}
```

**Comment by bcomnes** [comment]
Does standard enforce this?

**Comment by mightyiam** [comment]
Indeed.

**Comment by bcomnes** [comment]
Yeah, totally: "Block must not be padded by blank lines."

**Comment by mightyiam** [comment]
I've been using standard-format for https://github.com/PolicyStat/combokeys/pull/28.

Brilliant time–saver.

Every bit of manual labor that it saves is pure gold for me.

**Comment by mightyiam** [comment]
Thank you.
