### ISSUE TITLE
Start of line semicolons for [ and (

### ISSUE THREAD

**Issue by jb55** [maxogden/standard-format#25]
Might need a new esformatter plugin for this one, regex adds unnecessary semicolons in some cases

```js
var x = 2
[1,2,3].map(function () {})
```
is incorrectly formatted to
```js
var x = 2
  [1,2,3].map(function () {})
```

in the current version

**Comment by bcomnes** [comment]
This is one of those cases where the array should be protected with a preceding semicolon right?

>Never start a line with ( or [
This is the only gotcha with omitting semicolons – automatically checked for you!
Always prefix with ; like this ;[1, 2, 3].join(' ')

So the correct format would be:
```js
var x = 2
;[1,2,3].map(function () {})
```
Right?

**Comment by jb55** [comment]
Right, except if you have a naive regex that simply inserts a semicolon at the start of each `[` line, standard will complain in cases where it's not needed, such as:

```js
if (true) {
  ;[1, 2, 3].map(function () {})
}
```

**Comment by bcomnes** [comment]
Good point.  I haven't had a chance to dive into esformatter plugins totally yet, but I *think* it has the ability to conditionally perform actions between the esformatter selectors.

**Comment by millermedeiros** [comment]
I just spent the last 30min implementing a basic version of the plugin to do this: https://github.com/millermedeiros/esformatter-semicolon-first - if anyone wants to maintain it I would gladly add as contributor and/or transfer the ownership of the project.. created just so you guys can use as a reference

**Comment by bcomnes** [comment]
Nice @millermedeiros!  Ill pitch in where I can.
