### ISSUE TITLE
Replace remaining regex with esformatter plugins

### ISSUE THREAD

**Issue by jb55** [maxogden/standard-format#26]
We're still relying on some regex to transform edge cases that esformatter can't handle out of the box. 

Through testing of large JS libraries, I've noticed regex tends to transform things destructively sometimes. So we'll need to write [esformatter plugins](https://github.com/millermedeiros/esformatter/wiki/Plugins) to handle these cases.
- [x] Spaces after `function` and before the function name: function &nbsp; &nbsp; &nbsp; foo () {}

This one doesn't seem plugin worthy, there should be an option for this in `esformatter`
- [ ] Extra start of file newlines
- [ ] Removing and adding semicolons where necessary ([esformatter-semicolons](http://npmrepo.com/esformatter-semicolons) doesn't seem to work)

You might be able to handle some of these with `esformatter.json` but I haven't had any luck.

**Comment by millermedeiros** [comment]
I believe most of the logic should/could be implemented as an esformatter plugin or as a standalone executable, that way the `standard-format` executable is just a way to run it over multiple files - see: https://github.com/bcomnes/esformatter-standard and the new pipe feature: https://github.com/millermedeiros/esformatter/issues/168

**Comment by millermedeiros** [comment]
also feel free to create new bugs and feature requests on esformatter. if you open a bug with a simplified test case with the input and expected output it should not be hard for us to fix it.

**Comment by millermedeiros** [comment]
spaces between function keyword and function name should be fixed when we release esformatter@0.6 (I just pushed a fix to master)

**Comment by feross** [comment]
You should use `standard --fix` instead of this package. `standard-format` isn't being actively maintained anymore.
