### ISSUE TITLE
Pass torture test

### ISSUE THREAD

**Issue by jb55** [maxogden/standard-format#27]
We should be able to pass a completely obfuscated / minified javascript file to `standard-format` and have it produce a valid Standard JS file

For example, a [random snippet](https://gist.githubusercontent.com/jb55/76fe8dc473a6fc2f6421/raw/03072ccf2e2b5a48e2ed1a78b6941d9ae3e0b78e/standard-format-torture.js) from google.com

**Comment by feross** [comment]
Great idea!

**Comment by bcomnes** [comment]
I'll write a test for this right now.

**Comment by bcomnes** [comment]
I pushed a .skip onto this test for now so that its easier to focus on the individual failing tests: `npm run failing`

**Comment by feross** [comment]
You should use `standard --fix` instead of this package. `standard-format` isn't being actively maintained anymore.
