### ISSUE TITLE
Remove automatic stdin detection

### ISSUE THREAD

**Issue by feross** [maxogden/standard-format#34]
FYI, I'm [removing automatic stdin detection](https://github.com/feross/standard/issues/72) in `standard`, so `standard-format` should probably follow suit so we can fix these vim and Syntastic issues: https://github.com/feross/standard/issues/65, https://github.com/feross/standard/issues/64

:+1:

**Comment by jb55** [comment]
:+1:

**Comment by feross** [comment]
Btw, I already removed stdin detection from `standard` and it fixed both issues with vim and Syntastic! 

The only reason to fix it here is just so users who are using `standard-format` directly get the same benefit. The user can select stdin by passing in `-` in the place of a filename (a la unix style) or just `--stdin`. https://github.com/feross/standard/blob/d7a98bceb86b258a93f8a97a172431c5d296306c/bin/cmd.js#L21-L25
