### ISSUE TITLE
Throws error when using ES 2015 modules

### ISSUE THREAD

**Issue by thetalecrafter** [maxogden/standard-format#35]
Since `standard` supports linting ES 2015, it would be cool if `standard-format` could also clean up code style for files using ES 2015.

`Unexpected reserved word` is thrown on `import`.

**Comment by feross** [comment]
Since `standard-format` just uses `esformatter`, it looks like we'll get free support when this issue is fixed: https://github.com/millermedeiros/esformatter/issues/192

**Comment by millermedeiros** [comment]
esprima still doesn't support the module syntax, that's why it throws the error.

this feature is on the esprima v2.2 roadmap.

**Comment by bcomnes** [comment]
https://github.com/millermedeiros/esformatter/issues/206 Should save us here.

**Comment by millermedeiros** [comment]
this is in fact being tracked by https://github.com/millermedeiros/esformatter/issues/311 - v0.7.0 should not throw errors since we replaced the parser from esprima to espree (which supports the module syntax)

**Comment by parro-it** [comment]
:+1: for module syntax supprt

**Comment by Flet** [comment]
Since esformatter was updated to 0.7.0, module syntax be working with the latest version 1.3.9.

Closing.
