### ISSUE TITLE
White Space after variable name

### ISSUE THREAD

**Issue by Flet** [maxogden/standard-format#38]
Setting `whiteSpace.after.VariableName` to 1 will fix cases cases where [space-infix-ops](http://eslint.org/docs/rules/space-infix-ops.html) rule is broken due to no white space.

For Example:
```
var x= 1
```

However this would also reformat cases where this space may be desired:
```
var aaaa = 'hello'
var z    = 'world'
```

Unfortunately, its not possible to specify white space as a range (`>=1` would be a good compromise).

Any thoughts here? Is allowing white space to line up values desirable?

**Comment by feross** [comment]
I thought extra white spaces were prohibited by standard.

**Comment by Flet** [comment]
Ah, space-infix-ops allows more spaces, but [no-multi-spaces](http://eslint.org/docs/rules/no-multi-spaces.html) does not allow it, which is also enabled for standard.

Thanks, this answers it.
