### ISSUE TITLE
Pick up JSX files?

### ISSUE THREAD

**Issue by justin808** [maxogden/standard-format#45]
Should standard-format pick up jsx files?

It seems that standard is picking up jsx files.

**Comment by Flet** [comment]
We're dependent on esformatter for formatting, which does not currently support JSX currently (I believe millermedeiros/esformatter/issues/206 is opened for this purpose?)

In the meantime, we could add the plugin https://github.com/royriojas/esformatter-jsx-ignore and include *.jsx in the default patterns.

**Comment by bcomnes** [comment]
Any drawbacks to that plugin?  @justin808 what do you think?

**Comment by justin808** [comment]
I don't know. I'd be happy to try this out in my example project: https://github.com/justin808/react-webpack-rails-tutorial/pull/25. I've been incorporating the eslint features that are matched up with the airbnb style guidelines. https://github.com/airbnb/javascript/pull/276.

**Comment by danawoodman** [comment]
Any updates on this? Would be great to have JSX formatting support!

**Comment by millermedeiros** [comment]
esformatter v0.7.0 will allow JSX files since we replaced the parser from esprima to espree; I should release it in the next week.

**Comment by Flet** [comment]
Excellent @millermedeiros thanks for the updates on all these issues! :sparkles:

**Comment by bcomnes** [comment]
I was planning (or open to someone else) on patching in that 1st plugin, but I'll have to get up to date with  0.7.

**Comment by saulshanabrook** [comment]
Anything I could do to help get this working with esformatter 0.7.x?

**Comment by Flet** [comment]
Looks like we have esformatter 0.7.0 in package.json, so the next step is to make this include .jsx files (its currently [only globbing .js files](https://github.com/maxogden/standard-format/blob/master/index.js#L61)).

So, we're just a pull request away :)

**Comment by kevinsimper** [comment]
@Flet I submitted a pull request :)

**Comment by Flet** [comment]
published to npm as `1.4.0`
