### ISSUE TITLE
--format callback indentation bugs

### ISSUE THREAD

**Issue by feross** [maxogden/standard-format#49]
Moved from https://github.com/feross/standard/issues/105 for @nathan7:

Produced from a `standard`-compliant repo using `standard --format`. This is the last thing preventing me from using `standard --format` as a pre-commit hook.

```
Error: Use JavaScript Standard Style (https://github.com/feross/standard)
  /home/nathan/src/github.com/then/promise/test/resolver-tests.js:56:12: Expected indentation of 12 characters.
  /home/nathan/src/github.com/then/promise/test/resolver-tests.js:101:12: Expected indentation of 12 characters.
  /home/nathan/src/github.com/then/promise/test/resolver-tests.js:142:10: Expected indentation of 10 characters.
```

``` diff
diff --git a/test/resolver-tests.js b/test/resolver-tests.js
index 559b5f7..3929b43 100644
--- a/test/resolver-tests.js
+++ b/test/resolver-tests.js
@@ -53,9 +53,9 @@ describe('resolver-tests', function () {
       describe('if promise is resolved', function () {
         it('nothing happens', function (done) {
           var thenable = {then: function (onComplete) {
-            setTimeout(function () {
-              onComplete(sentinel)
-            }, 50)
+              setTimeout(function () {
+                onComplete(sentinel)
+              }, 50)
           }}
           new Promise(function (resolve) {
             process.nextTick(function () {
@@ -98,9 +98,9 @@ describe('resolver-tests', function () {
       describe('if promise is resolved', function () {
         it('nothing happens', function (done) {
           var thenable = {then: function (onComplete) {
-            setTimeout(function () {
-              onComplete(sentinel)
-            }, 50)
+              setTimeout(function () {
+                onComplete(sentinel)
+              }, 50)
           }}
           new Promise(function (resolve, reject) {
             process.nextTick(function () {
@@ -139,9 +139,9 @@ describe('resolver-tests', function () {
     describe('if promise is resolved', function () {
       it('nothing happens', function (done) {
         var thenable = {then: function (onComplete) {
-          setTimeout(function () {
-            onComplete(sentinel)
-          }, 50)
+            setTimeout(function () {
+              onComplete(sentinel)
+            }, 50)
         }}
         new Promise(function (resolve, reject) {
           resolve(thenable)
```

**Comment by bcomnes** [comment]
Esformatter has fairly well defined indentation rules, and I don't really see any particular advantage to one over another here.   Both are `standard` compliant, and both express an opinion on how nesting indentation should behave.  I'll definitely keep my eyes open on how to make these adjustments, but I personally like how gofmt handles this kind of thing:

>Since Go code is meant to be formatted automatically by gofmt, **some style must be chosen**. That style may differ from what you've used in C or Java, but Go is a new language and **gofmt's style is as good as any other** - https://golang.org/doc/faq#semicolons

**Comment by nathan7** [comment]
The issue here is that the output as it is violates the "braces must end at the same indentation level" rule. And `standard` balks at that. I'd like to be able to run my source code through `standard --format` when my editor saves, automatically, like I do with `gofmt`, and end up with code that passes the indentation checks.

**Comment by bcomnes** [comment]
Oh your totally right, I see now.  Lets get that fixed

**Comment by neckro** [comment]
I'm having a very similar problem (version 1.6.8).  It's happening in multiple circumstances, but I've distilled it down to a short test case (post-format):

```
window.define(function (require) {
  return window.extend({
    someFunc: function () {
      return window.do('something')
        .bind(this)
        .then(function (response) {
          return
        }).caught(function (e) {
        window.statement('statement 1')
        window.statement('statement 2')
        window.statement('statement 3')
        if (window.statement) {
          return
        }
      })
    }
  })
})
```
If the `.caught` is moved down to the next line it formats correctly.  This is preventing my using this as a pre-commit hook, like the original reporter.  `standard -F` formats the file incorrectly and then immediately complains that the indentation doesn't meet spec.

**Comment by bcomnes** [comment]
This is a serious issue, since formatted output is actually resulting in a failed lint.

In the meantime, the work around is to do something like:

```
window.define(function (require) {
  return window.extend({
    someFunc: function () {
      return window.do('something')
        .bind(this)
        .then(function (response) {
          return
        }).caught(handleError)
    }
  })
})

function handleError (e) {
  window.statement('statement 1')
  window.statement('statement 2')
  window.statement('statement 3')
  if (window.statement) {
    return
  }
}
```

Looking through https://github.com/maxogden/standard-format/blob/master/rc/esformatter.json I don't see any particular hook that I can tweak to fix this, and vanilla es-formatter has a similar output by default:

![](http://ipfs.pics/ipfs/QmbVFPtvJ7ovfHF7Chp89xA4a17U6uiFYeJmPz5JmzD9ck)

Does anyone else see what options that might help here?  Otherwise it might be a case of an upstream issue.

**Comment by feross** [comment]
You should use `standard --fix` instead of this package. `standard-format` isn't being actively maintained anymore.
