### ISSUE TITLE
i really need standard-format to add spaces

### ISSUE THREAD

**Issue by soldair** [maxogden/standard-format#54]
in this case `if(`
and in the object case `{a:b,c:d}`

i have really really terrible vision and when i don't have my contacts or only one contact in like now identifying these missing spaces is exceptionally time consuming. please help!

funnily enough i have no issues picking args by name etc with spaces missing this is probably just habit/repetition though.

a pointer to where i can add this in the code and ill make a pr

**Comment by feross** [comment]
Take a look at https://github.com/maxogden/standard-format/blob/master/rc/esformatter.json. This is where the config for `esformatter` is defined.

**Comment by Flet** [comment]
Added tests for both of these cases: https://github.com/maxogden/standard-format/commit/d4351bc6a0e3da85b4d38efff6a93d8d27324ce2

Also added a fix for the space after if: https://github.com/maxogden/standard-format/commit/20d40294e38e6c0e532821fa0fdd54d8e517778e

But the space after the commit is a bit trickier. There does not seem to be an esformatter hook to address it directly... asking here to be sure:  millermedeiros/esformatter#313

**Comment by feross** [comment]
You should use `standard --fix` instead of this package. `standard-format` isn't being actively maintained anymore.
