### ISSUE TITLE
standard-format doesn't remove trailing semicolons if they're followed by a comment

### ISSUE THREAD

**Issue by pdehaan** [maxogden/standard-format#55]
```sh
$ standard-format --version
1.3.6
```

### Steps to reproduce:
1. Create a new file, _foo.js_, w/ the following code:

    ```js
    var config = {
      consumer_key: consumer_key,
      access_token: access_token
    }; // useful comment
```

2. Run the following Terminal command: `$ standard-format -w foo.js`, or the following code to format and lint the code using **standard**:
    ```sh
    $ standard --format foo.js
    standard: Use JavaScript Standard Style (https://github.com/feross/standard)
      /Users/pdehaan/dev/tmp/pocketapi-test/foo.js:12:2: Extra semicolon.
    $ standard --version # 3.7.0
```

### Actual results:
The semicolon isn't removed during auto-formatting.

### Expected results:
The semicolon is removed.

**Comment by bcomnes** [comment]
I'll take a look at this in the morning.  

--
Bret Comnes
http://bret.io

**Comment by bcomnes** [comment]
Added a test for this.   Its not obvious how to fix this right now.  I'll try to address it when I have some more time, or anyone else can take a stab at it.

**Comment by pdehaan** [comment]
I think this is also not working w/ multiline comments (let me know if you want a separate bug since the PR already landed)

Case:

```js
var config = {
  consumer_key: consumer_key,
  access_token: access_token
}; /* useful comment */
```

**Comment by bcomnes** [comment]
@pdehaan yes please

**Comment by pdehaan** [comment]
@bcomnes You got it! Filed multiline comment issue as #60
