### ISSUE TITLE
atom plugin

### ISSUE THREAD

**Issue by zeke** [maxogden/standard-format#65]
I'm happy to run `standard --format` on the command line, but it would be nice to have  a command right inside atom.app. Does such a thing exist? A [search for atom packages](https://atom.io/packages/search?q=standard) turned up empty.

I suspect this wouldn't be too hard to make, but have yet to dive into the world of atom plugin authoring...

**Comment by bcomnes** [comment]
I would be happy to start one, or help someone else who wants to do it.  The [sublime plugin](https://github.com/bcomnes/sublime-standard-format) was actually way easier than I expected.  First step is finding other auto-formatter plugins for atom to get an an idea how others have done it. 

(Side note: Just started a new job so I've been a bit preoccupied with all of that.)

**Comment by bcomnes** [comment]
Been playing around with Atom more and more.  Damn, its gotten so much better lately.  

Anyway, just wanted to say I'm definitely on board with starting/helping on an atom plugin.

**Comment by zeke** [comment]
@bcomnes let me know when you want an alpha tester. :)

**Comment by ricardofbarros** [comment]
I have plans to introduce in [linter-js-standard](https://github.com/ricardofbarros/linter-js-standard) a command with that purpose on Atom Command Palette.

**Comment by bcomnes** [comment]
@ricardofbarros Good stuff!  It [made sense to split up](https://github.com/Flet/SublimeLinter-contrib-standard/pull/11#issuecomment-88623026) the linter and the formatter plugins for sublime.  Not sure if those are similar concerns in atom.

**Comment by ricardofbarros** [comment]
@bcomnes You gave a nice list arguments, that has changed my mind about the possibility of introducing format commands to the plugin. Like you said we shouldn't put features like this (standard-format) inside the AtomLinter framework, it does indeed more sense to build a new plugin with that purpose.

**Comment by stephenkubovic** [comment]
I took a first stab at an Atom plugin for this (actually published it moments before finding this thread).

https://atom.io/packages/standard-formatter

Let me know what you think.

**Comment by ricardofbarros** [comment]
Nice @stephenkubovic  :+1:

**Comment by bcomnes** [comment]
Rad ty @stephenkubovic !

**Comment by bcomnes** [comment]
Closed by https://github.com/maxogden/standard-format/pull/81
