### ISSUE TITLE
Extract non-standard-specific code

### ISSUE THREAD

**Issue by wbinnssmith** [maxogden/standard-format#66]
Would you guys be open to extracting all the non-standard specific code (basically everything but the `esformatter.json` and the regexes in `index.js`) into its own module? This would allow for a whole ecosystem of opinionated formatter clis with not much more than an `esformatter.json`.

I'd love to help if you're all open to it.

**Comment by Flet** [comment]
I believe esformatter will do this via it's CLI if provided the esformatter json:
https://github.com/millermedeiros/esformatter/blob/master/README.md#cli

The next problem is crwating an esformatter json file... So I had this thought and wanted to take it a step further so I created https://github.com/Flet/eslint-to-esformatter 

Its a WIP but the idea is to take any eslint config and output an esformatter json. With this it would be easy to make a formatter CLI tool that works on any eslint config in-place.

**Comment by feross** [comment]
You should use `standard --fix` instead of this package. `standard-format` isn't being actively maintained anymore.
