### ISSUE TITLE
update to esformatter ^0.7.0

### ISSUE THREAD

**Issue by seeekr** [maxogden/standard-format#74]
There's an issue in esformatter 0.6.x that makes it break on some (very common, for me at least) ES6 code. See issue here: https://github.com/millermedeiros/esformatter/issues/324
But that issue is fixed in 0.7.0 apparently, so I'd appreciate an update of that dep!
I'm using feross/standard and it in turn uses this lib and so it'd be nice to somehow work out the updating of the esformatter dep :) If I should also cross-post this issue on that other repo, then please let me know! (EDIT: Well, I just did post it over there as well, not being sure where it really belongs, who's talking to who here and how :))

Thanks!

**Comment by bcomnes** [comment]
I'm all for this, but just haven't had time lately.  PRs might make it happen sooner than later (and should be fairly easy?)  Prioritizing this on my todos.

**Comment by Flet** [comment]
Agree here too!  Happy to review a PR :)

**Comment by feross** [comment]
Published standard-format 1.3.7 that uses esformatter 0.7.0.

**Comment by bcomnes** [comment]
🎉TY feross
