### ISSUE TITLE
Whitespace is inserted in wrong place for class function

### ISSUE THREAD

**Issue by ratson** [maxogden/standard-format#75]
As suggested in https://github.com/feross/standard/issues/164,
the following code should be a well-formatted code,

```
class Bug {
  fix (author) {}
}
```

but it is transformed to

```
class Bug {
  fix( author) {}
}
```

**Comment by sweco-sebhar** [comment]
:+1:

**Comment by 0x80** [comment]
I just ran into this issue as well. But it's broader then just the function definition:


```javascript
export default class ActiveMeeting extends Component {
  renderAttendees() {
    return this.props.meeting.attendees.map((attendee) => {
      return <Attendee key={attendee.displayName} profile={attendee}/>
    })
  }
}
```

turns into

```javascript
export default class ActiveMeeting extends Component {
  renderAttendees() {
    return this.props.meeting.attendees.map((attendee) => {
      return <Attendee key={attendee.displayName} profile={attendee}/>
      })
    }
  }
```

The indentation is messed up, and my linter wont accept that of course. I use the standard-format on file save and because of this I will have to switch it off and manually correct whitespace style.

also

```javascript
export default class App extends Component {
  constructor(props) {
  }
}
```
turns into

```javascript
export default class App extends Component {
  constructor( props) {
  }
}
```
Notice the extra whitespace before props. The standard linter will complain about this too.

These issues are not happaning with esformatter defaults

**Comment by 0x80** [comment]
Actually this is an esformatter issue. If you add semicolons it goes right. But this is a problem obviously because standard-format strips semicolons.

**Comment by 0x80** [comment]
I'll put this in a different issue

**Comment by 0x80** [comment]
[Here](http://requirebin.com/?gist=a8d74c612f35f3af3615) I've used the current standard-format whitespace rules to highlight a few problems with es6 related syntax. Hope it helps.

**Comment by RanzQ** [comment]
This seems to make Sublime setting `format_on_save` unusable.

**Comment by Flet** [comment]
I think this PR to `esformatter` solves half of this problem.
https://github.com/millermedeiros/esformatter/pull/355

**Comment by Flet** [comment]
For the other half... (which is the space after the method name) I don't know if its possible without more code change in `esformatter`. There doesn't seem to be a way to easily address the method name itself (I could be wrong though).

**Comment by Flet** [comment]
@millermedeiros any thoughts on this? It seems there is not a way to control formatting around the method name inside of a class in esformatter. Do you think esformatter needs a code change to support this?

**Comment by millermedeiros** [comment]
@Flet probably need a new rule for the `MethodName` inside the [`FunctionExpression` hook](https://github.com/millermedeiros/esformatter/blob/master/lib/hooks/FunctionExpression.js#L13-L17) that way we can have different rules for regular function expressions and methods.

**Comment by millermedeiros** [comment]
FYI, esformatter@0.8.2 was just released and includes a new setting `whiteSpace.after.MethodDefinitionName` (see: https://github.com/millermedeiros/esformatter/commit/274eb877f3cd47663723548839bae60e156ccf0c)

also fixed a lot of bugs related to indentation and ES6 in general.

**Comment by feross** [comment]
You should use `standard --fix` instead of this package. `standard-format` isn't being actively maintained anymore.
