### ISSUE TITLE
enable esformatter-semicolon-first plugin

### ISSUE THREAD

**Issue by Flet** [maxogden/standard-format#76]
We found that `esformatter-semicolon-first` is causing `import` statements to fail.

Issue opened here:
millermedeiros/esformatter-semicolon-first#2

With commit https://github.com/maxogden/standard-format/commit/10f6e4696f37f521b52337968680923546b6e2b2, the plugin has been disabled and the semicolon first tests have been moved to tests/failing.

Once the issue above is resolved, we can re-enable this plugin.

**Comment by millermedeiros** [comment]
`esformatter-semicolon-first@1.1.0` was published to npm including the fix.

**Comment by Flet** [comment]
Published as `1.3.10`
