### ISSUE TITLE
Is JSX supported or not

### ISSUE THREAD

**Issue by 0x80** [maxogden/standard-format#82]
So I had [this](https://github.com/royriojas/esformatter-jsx/issues/8) issue with indentation, which I reported with esformatter. It turned out to be a jsx issue so I reported to the esformatter-jsx plugin, and it turned out to work fine. 

Now I realize that esformatter-jsx is not included in standard-format so I'm assuming that is why it doesn't work :)

My code and future projects will be es6 /react / jsx based, and currently standard-format doesn't cut it. Are you planning to include the jsx plugin or is my only options to use esformatter with an adapted config?

**Comment by Flet** [comment]
Since `standard` comes with built-in jsx linting via [eslint-config-standard-react](https://github.com/feross/eslint-config-standard-react), it may make sense to include support for it, especially if its easy enough to do via a plugin.

Any others have thoughts on this?

**Comment by bcomnes** [comment]
I'm okay with trying it out but have been unavailable to put much in the last couple months.  @jb55 @maxogden @feross ?

**Comment by feross** [comment]
Yeah, we should try adding it to `standard-format` since `standard` supports jsx out of the box.

**Comment by feross** [comment]
@0x80 If you want to take a stab at sending a PR, that's probably the fastest way to get this fixed: https://github.com/maxogden/standard-format

**Comment by 0x80** [comment]
@feross I will give it a try. I really like what you guys did with the standard(-format) thing and the last missing piece for me is jsx support so the least I can do is put in a little effort :)

**Comment by 0x80** [comment]
I just committed a PR. Haven't added any specific tests for JSX, apart from the bug I was experiencing with indentation. That turned out to be a related to a standard esformatter indent setting.

**Comment by feross** [comment]
Thanks - this is released as v1.6.0.

**Comment by 0x80** [comment]
:+1:
