### ISSUE TITLE
backslashes stripped out of strings

### ISSUE THREAD

**Issue by ngoldman** [maxogden/standard-format#84]
I noticed `standard -F` stripped backslashes out of a string that actually needed to have backslashes in there. Case in point: https://github.com/Esri/koop/pull/207#discussion_r35277882

**Comment by Flet** [comment]
Hmm, may be an issue with [esformatter-quotes](https://github.com/millermedeiros/esformatter-quotes) plugin...

Settings:
```
  "quotes": {
    "type": "single",
    "avoidEscape": true
  }
```

**Comment by Flet** [comment]
Looks one feature of this plugin is to remove unnecessary escaping. '

It considers the escaping on that string to be unnecessary since it's wrapped in single quotes.
So, `'\"ESRI Shapefile\"'` is technically the same as `'"ESRI Shapefile"'`.

Do you need a `\` to be part of the actual string, or was this just to escape the `"`?

**Comment by ngoldman** [comment]
@Flet afaik the `\` is necessary in our case as it's meant to be concatenated and executed on the command line.

**Comment by bcomnes** [comment]
does escaping the `\` work?

**Comment by ngoldman** [comment]
@bcomnes the result if I do that is kind of hilarious. If I escape the escape characters, I start with this:

`'\\"ESRI Shapefile\\"'`

If I run `standard -F` it strips off the first ones, and I end up with:

`'\"ESRI Shapefile\"'`

Running `standard -F` a second time, I end up with:

``'"ESRI Shapefile"'``

**Comment by Flet** [comment]
Looks like the plugin does not respect escaping `\`:

Formatting the same line three times:
`var lorem = '\\"ESRI Shapefile\\"';` -> 
`var lorem = '\"ESRI Shapefile\"';` ->
 `var lorem = '"ESRI Shapefile"'`

So, I think the plugin is broken :(

^^ yep, same thing I see @ngoldman!

**Comment by bcomnes** [comment]
😂

**Comment by feross** [comment]
Looks like the plugin is broken.

But I'm pretty sure the original code also doesn't need any `\`. You can verify this in the console:

```
$ node

> '\"ESRI Shapefile\"'
'"ESRI Shapefile"'

> '"ESRI Shapefile"'
'"ESRI Shapefile"'
```

When you use the escape character unnecessarily, it's ignored.

**Comment by feross** [comment]
I filed an issue: https://github.com/millermedeiros/esformatter-quotes/issues/12

**Comment by ngoldman** [comment]
Thanks @feross, further investigation proves you are correct.

**Comment by millermedeiros** [comment]
`esformatter-quotes@1.0.3` (published last week) should fix this

**Comment by feross** [comment]
Nice, we use `^1.0.0` in package.json, so no update is required to `standard-format` for users to get the fix :+1:

**Comment by ngoldman** [comment]
:tophat:
:grin:
:necktie::+1: 
:jeans:
