### ISSUE TITLE
Indentation bug after do-while

### ISSUE THREAD

**Issue by thr0w** [maxogden/standard-format#86]
expected:

``` javascript
function x()
{
  var i=0
  do {
    i++
  } while(i<10)
  console.log(i);
}
```

bug last do lines has wrong indent

``` javascript
function x()
{
  var i=0
  do {
    i++
  } while(i<10)
    console.log(i);
  }
```

**Comment by bcomnes** [comment]
Got your test merged in, and it lives in failing at the moment.  Will have to look into this some more.

**Comment by feross** [comment]
You should use `standard --fix` instead of this package. `standard-format` isn't being actively maintained anymore.
