### ISSUE TITLE
ObjectExpressionClosingBrace line break not respected

### ISSUE THREAD

**Issue by Whoaa512** [maxogden/standard-format#88]
This is a snippet of code that from a repo using [standard](https://www.npmjs.com/package/standard) with the [babel-eslint](https://www.npmjs.com/package/babel-eslint) parser. However when I run `standard -F` I get the following unexpected changes. Any ideas why this is happening?

``` diff
@@ -26,8 +26,7 @@ let client = new elasticsearch.Client({
     return {
       resolve,
       reject,
-      promise
-    }
+    promise}
   }
 })

@@ -51,23 +50,22 @@ server.use(restify.bodyParser())

 server.post('/log/:index/:type', function (req, res, next) {
   logger.info('Received some logs', req.body)
   let {index, type} = req.params
   let doc = {
     index,
     type,
-    body
-  }
+  body}
```

**Comment by drewhamlett** [comment]
+1

**Comment by nickpoorman** [comment]
+1

**Comment by nickpoorman** [comment]
Doesn't break if you put it all on one line

**Comment by feross** [comment]
You should use `standard --fix` instead of this package. `standard-format` isn't being actively maintained anymore.
