### ISSUE TITLE
Double quotes are not replaced with single quotes in jsx tags

### ISSUE THREAD

**Issue by TheLudd** [maxogden/standard-format#94]
If I have this: `<div className="my-class">` the double quotes are not replaced with single quotes even though `standard` reports it as an error.

**Comment by feross** [comment]
Is that in your JSX?

**Comment by TheLudd** [comment]
What do you mean exactly?

I have jsx files with tag attributes using double quotes, yes.

**Comment by feross** [comment]
Looks like esformatter doesn't replace quotes in JSX. You probably need to send them a PR to fix this!

**Comment by TheLudd** [comment]
Will do
