### ISSUE TITLE
indentation issues on jsx

### ISSUE THREAD

**Issue by jney** [maxogden/standard-format#99]
I'm just trying `standard-format` on `atom` and i noticed behaviours i didn't expected working with `jsx`.

having this source file : 

```javascript
export class Foo extends React.Component {
  render() {
    return (
      <div></div>
    )
  }
}
```

is formated with alignement on parentheses : 
 
```javascript
export class Foo extends React.Component {
  render() {
    return (
    <div></div> // <= notice here 
    )
  }
}
```

and playing with parameters : 

```javascript
    return (
      <div>
        <span
          foo={bar}
          bar={baz} />
      </div>
    )
```

each parameter is aligned to the root node

```javascript
    return (
    <div>
        <span
    foo={bar}
    bar={baz} />
      </div>
    )
```

**Comment by bcomnes** [comment]
Which version of `standard-format` are you running?  I just updated the JSX formatting lib and might still have some settings I need to tweak.

**Comment by bcomnes** [comment]
Added a test-case for this.  Our JSX test sample size is pretty small so thanks for pointing this out.

**Comment by jney** [comment]
you're very active on this project, thank you.
it was the version provided with `atom`'s `standard-formatter` (`1.6.0`) : https://github.com/stephenkubovic/atom-standard-formatter/blob/master/package.json#L23

**Comment by jonathanong** [comment]
seeing this on 1.6.7

input:

```js
'use strict'

import React from 'react'
import { Route, DefaultRoute } from 'react-router'

import { App } from '../lite/component/app.jsx'
import { VideoUploader } from '../lite/component/video-uploader.jsx'
import { ExperienceEditor } from '../lite/component/experience-editor.jsx'
import { Publisher } from '../lite/component/publish.jsx'

export const routes = (
  <Route name="lite" path="/" handler={App}>
    <DefaultRoute name="upload" handler={VideoUploader} />
    <Route name="customize" path="e/:experienceId" handler={ExperienceEditor} />
    <Route name="release" path="e/:experienceId/r/:releaseId" handler={Publisher} />
  </Route>
)
```

output:

```js
'use strict'

import React from 'react'
import { Route, DefaultRoute } from 'react-router'

import { App } from '../lite/component/app.jsx'
import { VideoUploader } from '../lite/component/video-uploader.jsx'
import { ExperienceEditor } from '../lite/component/experience-editor.jsx'
import { Publisher } from '../lite/component/publish.jsx'

export const routes = (
<Route name="lite" path="/" handler={App}>
    <DefaultRoute name="upload" handler={VideoUploader} />
    <Route name="customize" path="e/:experienceId" handler={ExperienceEditor} />
    <Route name="release" path="e/:experienceId/r/:releaseId" handler={Publisher} />
  </Route>
)
```

**Comment by bcomnes** [comment]
I mucked around with the jsx formatter settings a bit and currently have the following at a loop:

(in branch https://github.com/bcomnes/standard-format/tree/jsx )

```jsx
'use strict'

import React from 'react'
import { Route, DefaultRoute } from 'react-router'

import { App } from '../lite/component/app.jsx'
import { VideoUploader } from '../lite/component/video-uploader.jsx'
import { ExperienceEditor } from '../lite/component/experience-editor.jsx'
import { Publisher } from '../lite/component/publish.jsx'

export const routes = function beep () {
  <Route name='lite' path='/' handler={App}>
    <DefaultRoute name='upload' handler={VideoUploader} />
    <Route name='customize' path='e/:experienceId' handler={ExperienceEditor} />
    <Route name='release' path='e/:experienceId/r/:releaseId' handler={Publisher} />
  </Route>
}

export class Foo extends React.Component {
  render() {
    return (
    <div>
      <span
        foo={bar}
        bar={baz}
        beep={boop}
        maxattr={four} />
    </div>
    )
  }
}

export default class Foo extends Component {
  renderPartial() {
    return this.props.bar.map((item) => {
      return <Bar key={item.foo} data={item} />
    })
  }
}
```

@jonathanong, @jney what are your thoughts on these results? better? worse? specific issues that are really bad or showstoppers?

**Comment by jney** [comment]
@bcomnes cool ! it looks more consistent, but shouldn't elements in parentheses be also indented ?

```javascript
return (
  <div>
    <span
      foo={bar}
      bar={baz}
      beep={boop}
      maxattr={four} />
  </div>
)
```

**Comment by feross** [comment]
@bcomnes feel free to send in your changes as a PR if they improve the situation here. :)

**Comment by bcomnes** [comment]
Wasn't quite ready to PR yet, and I haven't had time to put a bow on it yet due to traveling.  But will do!

**Comment by bcomnes** [comment]
@jney I kinda agree with you, but was not finding a way to get that from my quick peek yesterday.

**Comment by nrw** [comment]
i'm encountering this too. would love to see a pr. 

```js
// this is the correct indentation
var React = require('react')
var Touchable = React.Touchable
var View = React.View

function renderView () {
  return <View>
    <Touchable>
      <View style={{
        alignSelf: 'stretch'
      }}>
        <Icon
          style={{width: 30, height: 30}}
        />
      </View>
    </Touchable>
  </View>
}
```

```js
// this is what standard-format 1.6.7 is doing to it
var React = require('react')
var Touchable = React.Touchable
var View = React.View

function renderView () {
  return <View>
    <Touchable>
      <View style={{
    alignSelf: 'stretch'
  }}>
        <Icon
  style={{width: 30, height: 30}}
  />
      </View>
    </Touchable>
  </View>
}
```

**Comment by bcomnes** [comment]
Issue https://github.com/feross/standard/issues/338 from @mblakele moved to here.

**Comment by LinusU** [comment]
I'm hitting this as well, would love a solution :)

**Comment by JoakimLofgren** [comment]
esformatter-jsx has version v4.1.2 available. Upgrading might fix this?

**Comment by chenxsan** [comment]
@JoakimLofgren Not really, check a [demo here](http://requirebin.com/embed?gist=0d67452e01754269660f#{"config":{"jsx":{"attrsOnSameLineAsTag":false,"maxAttrsOnTag":0,"firstAttributeOnSameLine":false,"alignWithFirstAttribute":false,"spaceInJSXExpressionContainers":"%20"}},"code":"//%20Paste%20your%20own%20code%20here...\n\n\n%20var%20Comment%20=%20React.createClass({\n%20%20render:%20function()%20{\n%20%20%20%20return%20(\n%20%20%20%20%20%20<div%20className=\"comment-hhh\"%20onClick={()=>{}}>\n%20%20%20%20%20%20%20%20<h2%20className=\"commentAuthor\">\n%20%20%20%20%20%20%20%20%20%20{this.props.author}\n%20%20%20%20%20%20%20%20</h2>\n%20%20%20%20%20%20%20%20{this.props.children}\n%20%20%20%20%20%20</div>\n%20%20%20%20);\n%20%20}\n});\n"}).

**Comment by Phisherman** [comment]
It still indents wrong.

```jsx
const App = () => {
  return (
  <div>
    <SearchBar />
  </div>
  )
}
```

should be

```jsx
const App = () => {
  return (
    <div>
      <SearchBar />
    </div>
  )
}
```
